apiVersion: v1
kind: Namespace
metadata:
  name: ibm-common-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-namespace-scope-operator
  namespace: ibm-common-services
  labels:
    app.kubernetes.io/instance: "ibm-namespace-scope-operator"
    app.kubernetes.io/managed-by: "ibm-namespace-scope-operator"
    app.kubernetes.io/name: "ibm-namespace-scope-operator"
    productName: IBM_Cloud_Platform_Common_Services
spec:
  selector:
    matchLabels:
      name: ibm-namespace-scope-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: ibm-namespace-scope-operator
        app.kubernetes.io/instance: ibm-namespace-scope-operator
        app.kubernetes.io/managed-by: "ibm-namespace-scope-operator"
        app.kubernetes.io/name: "ibm-namespace-scope-operator"
        productName: IBM_Cloud_Platform_Common_Services
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: "FREE"
    spec:
      serviceAccountName: ibm-namespace-scope-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - command:
        - /namespace-scope-operator-manager
        image: icr.io/cpopen/ibm-namespace-scope-operator:latest
        imagePullPolicy: IfNotPresent
        name: ibm-namespace-scope-operator
        env:
        - name: OPERATOR_NAME
          value: "ibm-namespace-scope-operator"
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
            ephemeral-storage: 256Mi
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      terminationGracePeriodSeconds: 10
