{{- $chartName := .Chart.Name }}
{{- $operatorNamespace := .Values.global.operatorNamespace }}

{{- $namespaces := .Values.global.tetheredNamespaces | default list -}}
{{- $namespaces = append $namespaces .Values.global.operatorNamespace -}}
{{- if .Values.global.instanceNamespace }}
  {{- $namespaces = append $namespaces .Values.global.instanceNamespace }}
{{- end }}
{{- range $i := $namespaces }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nss-managed-role-from-{{ $operatorNamespace }}
  namespace: {{ $i }}
  labels:
    component-id: {{ $chartName }}
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - pods
  - verbs:
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
  - verbs:
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - operator.ibm.com
    resources:
      - namespacescopes
      - namespacescopes/status
      - namespacescopes/finalizers
  - verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
      - create
    apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - serviceaccounts
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-namespace-scope-operator
  namespace: {{ $i }}
  labels:
    component-id: {{ $chartName }}
subjects:
  - kind: ServiceAccount
    name: ibm-namespace-scope-operator
    namespace: {{ $operatorNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nss-managed-role-from-{{ $operatorNamespace }}
---
{{- end }}
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/instance: ibm-namespace-scope-operator
    app.kubernetes.io/managed-by: ibm-namespace-scope-operator
    app.kubernetes.io/name: ibm-namespace-scope-operator
    component-id: {{ .Chart.Name }}
  name: ibm-namespace-scope-operator
  namespace: {{ .Values.global.operatorNamespace }}