kind: Deployment
apiVersion: apps/v1
metadata:
  name: ibm-namespace-scope-operator
  labels:
    app.kubernetes.io/instance: ibm-namespace-scope-operator
    app.kubernetes.io/managed-by: ibm-namespace-scope-operator
    app.kubernetes.io/name: ibm-namespace-scope-operator
    productName: IBM_Cloud_Platform_Common_Services
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-namespace-scope-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ibm-namespace-scope-operator
        app.kubernetes.io/managed-by: ibm-namespace-scope-operator
        app.kubernetes.io/name: ibm-namespace-scope-operator
        name: ibm-namespace-scope-operator
        productName: IBM_Cloud_Platform_Common_Services
      annotations:
        operators.operatorframework.io/builder: operator-sdk-v1.32.0
        operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
        productID: 068a62892a1e4db39641342e592daa25
        repository: 'https://github.com/IBM/ibm-namespace-scope-operator'
        support: IBM
        operators.openshift.io/infrastructure-features: '["disconnected"]'
        alm-examples: |-
          [
            {
              "apiVersion": "operator.ibm.com/v1",
              "kind": "NamespaceScope",
              "metadata": {
                "name": "namespacescope"
              },
              "spec": {
                "namespaceMembers": [
                  "ibm-common-services",
                  "default"
                ],
                "restartLabels": {
                  "intent": "projected"
                }
              }
            }
          ]
        capabilities: Seamless Upgrades
        productName: IBM Cloud Platform Common Services
        containerImage: '{{ .Values.imagePullPrefix }}/{{ .Values.imageRegistryNamespaceOperator }}/ibm-namespace-scope-operator:{{ .Values.imageTag }}'
        productMetric: FREE
    spec:
      restartPolicy: Always
      serviceAccountName: ibm-namespace-scope-operator
      schedulerName: default-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      terminationGracePeriodSeconds: 10
      securityContext: {}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              ephemeral-storage: 256Mi
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          name: ibm-namespace-scope-operator
          command:
            - /namespace-scope-operator-manager
          env:
            - name: OPERATOR_NAME
              value: ibm-namespace-scope-operator
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: '{{ .Values.imagePullPrefix }}/{{ .Values.imageRegistryNamespaceOperator }}/{{ .Values.operatorImage }}:{{ .Values.operatorVersion }}'
      serviceAccount: ibm-namespace-scope-operator
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600