apiVersion: operator.ibm.com/v1
kind: NamespaceScope
metadata:
  labels:
    foundationservices.cloudpak.ibm.com: nss
    component-id: {{ .Chart.Name }}
    {{- with .Values.cpfs.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: common-service
  namespace: {{ .Values.global.operatorNamespace }}
spec:
  csvInjector:
    enable: true
  license:
    accept: {{ .Values.global.licenseAccept }}
  namespaceMembers:
    - {{ .Values.global.operatorNamespace }}
    - {{ .Values.global.instanceNamespace }}
    {{- range $v := $.Values.global.tetheredNamespaces }}
    - {{ $v }}
    {{- end }}
  restartLabels:
    intent: projected