apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: "ibm-namespace-scope-operator"
    app.kubernetes.io/managed-by: "ibm-namespace-scope-operator"
    app.kubernetes.io/name: "ibm-namespace-scope-operator"
  name: ibm-namespace-scope-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-namespace-scope-operator
subjects:
  - kind: ServiceAccount
    name: ibm-namespace-scope-operator
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: "ibm-namespace-scope-operator"
    app.kubernetes.io/managed-by: "ibm-namespace-scope-operator"
    app.kubernetes.io/name: "ibm-namespace-scope-operator"
  name: ibm-namespace-scope-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-namespace-scope-operator
subjects:
  - kind: ServiceAccount
    name: ibm-namespace-scope-operator