apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-namespace-scope-operator
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - pods
  - verbs:
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
  - verbs:
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - operator.ibm.com
    resources:
      - namespacescopes
      - namespacescopes/status
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-namespace-scope-operator
rules:
# manage mutation webhook configuration
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch