---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-namespace-scope-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-namespace-scope-operator
subjects:
- kind: ServiceAccount
  name: ibm-namespace-scope-operator
