apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-namespace-scope-operator
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
      - deletecollection
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
  - verbs:
      - create
      - get
      - list
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - delete
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - patch
      - watch
    apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
  - verbs:
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - operator.ibm.com
    resources:
      - namespacescopes
      - namespacescopes/status
      - namespacescopes/finalizers
  - verbs:
      - get
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - serviceaccounts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-namespace-scope-operator
rules:
# manage mutation webhook configuration
  - verbs:
      - get
      - list
      - update
      - watch
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces