apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: "ibm-namespace-scope-operator"
    app.kubernetes.io/managed-by: "ibm-namespace-scope-operator"
    app.kubernetes.io/name: "ibm-namespace-scope-operator"
  name: ibm-namespace-scope-operator