kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-namespace-scope-operator-{{ .Values.global.operatorNamespace }}
  labels:
    component-id: {{ .Chart.Name }}
    {{- if .Values.cpfs.labels }}
      {{- with .Values.cpfs.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}
    {{- if .Values.cpfs.clusterLabels }}
      {{- with .Values.cpfs.clusterLabels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}
rules:
  - verbs:
      - get
      - list
      - update
      - watch
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-namespace-scope-operator-{{ .Values.global.operatorNamespace }}
  labels:
    component-id: {{ .Chart.Name }}
    {{- if .Values.cpfs.labels }}
      {{- with .Values.cpfs.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}
    {{- if .Values.cpfs.clusterLabels }}
      {{- with .Values.cpfs.clusterLabels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end}}
subjects:
  - kind: ServiceAccount
    name: ibm-namespace-scope-operator
    namespace: {{ .Values.global.operatorNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-namespace-scope-operator-{{ .Values.global.operatorNamespace }}
